insert into "user" (id, name, surname, email, username, password, status) values (default, 'Tadeo', 'Cawthery', 'tcawthery0@behance.net', 'user1', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Cara', 'Sabin', 'csabin1@amazon.de', 'user2', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Maisie', 'Peepall', 'nikolaakv@gmail.com', 'user3', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Ruggiero', 'Boij', 'rboij3@imgur.com', 'user4', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Caz', 'Gavrieli', 'cgavrieli4@woothemes.com', 'user5', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Correy', 'Klimentyonok', 'cklimentyonok5@businessinsider.com', 'user6', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Doloritas', 'Bonafacino', 'dbonafacino6@mapy.cz', 'user7', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Lu', 'Uren', 'luren7@nhs.uk', 'user8', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Talyah', 'Czaja', 'tczaja8@networksolutions.com', 'user9', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, username, password, status) values (default, 'Dalston', 'MacCartan', 'dmaccartan9@so-net.ne.jp', 'user10', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
--All passwords are 123123