insert into "post" (id, private, text, "created_date", id_user, id_group, deleted) values (default, true, '', '2021-12-27', 3, 9, false);
insert into "post" (id, private, text, "created_date", id_user, deleted) values (default, false, '', '2022-04-02', 3, false);
insert into "post" (id, private, text, "created_date", id_user, id_group, deleted) values (default, false, '', '2021-12-14', 5, 1, false);
insert into "post" (id, private, text, "created_date", id_user, id_group, deleted) values (default, false, '', '2022-05-16', 7, 9, false);
insert into "post" (id, private, text, "created_date", id_user, id_group, deleted) values (default, false, '', '2021-11-17', 1, 2, false);
insert into "post" (id, private, text, "created_date", id_user, id_group, deleted) values (default, false, '', '2022-03-23', 7, 10, false);
insert into "post" (id, private, text, "created_date", id_user, id_group, deleted) values (default, false, '', '2022-06-30', 7, 5, false);
insert into "post" (id, private, text, "created_date", id_user, id_group, deleted) values (default, false, '', '2022-01-20', 10, 3, false);
insert into "post" (id, private, text, "created_date", id_user, id_group, deleted) values (default, true, '', '2022-01-04', 10, 4, false);
insert into "post" (id, private, text, "created_date", id_user, deleted) values (default, false, '', '2022-11-01', 3, false);
