insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'Great!', '2022-08-22', false, 1, null, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'Have a great day!', '2021-12-10', true, 6, null, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'Thank you.', '2022-04-05', false, 8, null, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'My brother!', '2022-03-29', false, 1, 3, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'I agree!', '2022-03-07', false, 2, 4, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'HAHAHAHAAH', '2022-03-17', false, 7, 2, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'Nice.', '2021-12-15', true, 2, 3, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'interesting...', '2022-05-24', true, 7, 4, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, 'Long comment.', '2022-07-16', false, 4, 4, 3);
insert into "comment" (id, text, "created_date", deleted, id_user, id_replied_to, id_post) values (default, ':-)', '2022-01-16', false, 3, 9, 3);
